# Generated by Django 5.2.6 on 2025-09-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinfo',
            name='delivery_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Number of delivery attempts'),
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='delivery_company',
            field=models.CharField(blank=True, help_text='Delivery company/logistics partner', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Delivery fee in Naira', max_digits=10),
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='delivery_status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed', 'Delivery Failed')], default='assigned', max_length=20),
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='failure_reason',
            field=models.TextField(blank=True, help_text='Reason for delivery failure', null=True),
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='last_attempt_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Delivery tracking number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, help_text='City for delivery', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_instructions',
            field=models.TextField(blank=True, help_text='Special delivery instructions', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='landmark',
            field=models.CharField(blank=True, help_text='Nearby landmark for easy delivery', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, help_text='State for delivery', max_length=100, null=True),
        ),
    ]
