# Generated by Django 5.2.6 on 2025-09-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_deliveryinfo_delivery_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(db_index=True, default=122112, editable=False, max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
