# Generated by Django 5.2.6 on 2025-09-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_brand_product_estimated_delivery_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_benefits',
            field=models.JSONField(blank=True, default=list, help_text="Product benefits in list format. Example: ['Saves time', 'Cost effective', 'Long lasting']"),
        ),
        migrations.AddField(
            model_name='product',
            name='product_details',
            field=models.JSONField(blank=True, default=list, help_text="Product details in list format. Example: ['High quality material', 'Durable construction', 'Easy to use']"),
        ),
    ]
