# Generated by Django 5.2.6 on 2025-09-25 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_product_benefits_product_product_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='Upload video file (MP4, WebM, or MOV recommended for web compatibility)', upload_to='products/videos/')),
                ('title', models.CharField(blank=True, help_text='Optional title for the video', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of the video content')),
                ('autoplay', models.BooleanField(default=True, help_text='Video will auto-play when visible (muted by default for web compatibility)')),
                ('loop', models.BooleanField(default=True, help_text='Video will loop continuously')),
                ('muted', models.BooleanField(default=True, help_text='Video will be muted by default (required for autoplay in most browsers)')),
                ('show_controls', models.BooleanField(default=True, help_text='Show video controls (play, pause, volume, etc.)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of video display (lower numbers first)')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured video (shown first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='products.product')),
            ],
            options={
                'ordering': ['-is_featured', 'order', 'created_at'],
            },
        ),
    ]
